/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agregar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ajustes` | `/ajustes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `/categoria/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/agregar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ajustes` | `/ajustes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownOutputParams; } | { pathname: `/categoria/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/agregar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ajustes${`?${string}` | `#${string}` | ''}` | `/ajustes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categorias${`?${string}` | `#${string}` | ''}` | `/categorias${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/movimientos${`?${string}` | `#${string}` | ''}` | `/movimientos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agregar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ajustes` | `/ajustes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownInputParams; } | `/categoria/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/categoria/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
